### PR TITLE
Laravel 5.4 support?

### PR DESCRIPTION
**Pull request by JackEllis**
This should work fine with Laravel 5.4?

### CODE REVIEW

**Comment by willemo** [comment]
It probably would. Have you tested it with 5.4?

**Comment by JackEllis** [comment]
Using in 5.4 now

**Comment by willemo** [comment]
Merged

**Comment by JackEllis** [comment]
Nice - v1.0.4?

**Comment by willemo** [comment]
v1.0.3, I already tagged it

**Pull request merged**
